
name: BuildJar
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3 # 核心：这行会自动帮你补齐缺失的 gradle 零件

      - name: Run Build
        run: |
          chmod +x gradlew
          ./gradlew jar
          
      - name: Save Result
        uses: actions/upload-artifact@v4
        with:
          name: tingshu-jar
          path: build/libs/*.jar
